name: Test

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
